### ISSUE TITLE
Can not find tool/preprocess.py

### ISSUE THREAD

**Issue by zhangjb416** [bryanyu1997/Data-Efficient-3D-Learner#2]
I did not find the data processing code (tool/preprocess.py) for RGBD datasets, which you mentioned in Readme.
Could you please provide this file?

**Comment by bryanyu1997** [comment]
Hi, I just update the [tools/preprocess.py](https://github.com/bryanyu1997/Data-Efficient-3D-Learner/master/tools/preprocess.py) missed in the repository. Thanks for your kindly reminder!
