### ISSUE TITLE
About the numbers of predicted vertices

### ISSUE THREAD

**Issue by Bingoang** [bryanyu1997/Data-Efficient-3D-Learner#3]
Hi~
I really appreciate your great work! But I met a problem which I've tried my best but still cannot solve it:
when I ran "python segmentation.py --config config/scannet_eval.yaml " to test on scannetv2-test-set, some predicted vertices numbers do not equal the input vertices numbers.
How do I set the threshold to make them match?
Thanks in adavance!

**Comment by bryanyu1997** [comment]
Hi, [the code here](https://github.com/bryanyu1997/Data-Efficient-3D-Learner/blob/master/segmentation.py#L80) filter the point clouds whose labels need to be ignored, please check the parameters are set correctly in config file, thanks!
